# 數值資料標準化

## 對應字典法

In [1]:
import pandas as pd
df = pd.read_csv('客戶聯絡狀況資料檔.csv')

df['婚姻'].unique()

array(['單身', '已婚', '離婚', '未知'], dtype=object)

In [2]:
dict1 = {'單身':1, '已婚':2, '離婚':3, '未知':4}
df['婚姻'].replace(dict1, inplace=True)
df

         年齡    工作  婚姻  學歷 聯絡方式  最後聯絡時間  聯絡次數  消費價格指數  消費信心指數  訂購
0      31.0   服務業   1  高中   手機   750.0     2  92.893   -46.2  一次
1      55.0    無業   2  高中   市話   154.0     8  94.465   -41.8  一次
2      27.0    主管   2  專科   手機   466.0     1  92.893   -46.2  頻繁
3      35.0    主管   2  大學   手機   222.0     1  93.075   -47.1  一次
4      29.0    藍領   1  國中   手機    85.0     2  92.893   -46.2  頻繁
...     ...   ...  ..  ..  ...     ...   ...     ...     ...  ..
40995  47.0    主管   2  大學   市話    76.0     1  93.918   -42.7  偶爾
40996  30.0    主管   2  大學   手機   438.0     2  92.469   -33.6  從未
40997  48.0    藍領   2  小學   手機   151.0     1  93.918   -42.7  從未
40998  50.0    經理   2  大學   市話   242.0     2  94.465   -41.8  從未
40999  29.0  自僱人士   1  大學   手機    88.0     1  93.200   -42.0  從未

[41000 rows x 10 columns]

In [3]:
dict2 = {1:'單身', 2:'已婚', 3:'離婚', 4:'未知'}
df['婚姻'].replace(dict2, inplace=True)
df

         年齡    工作  婚姻  學歷 聯絡方式  最後聯絡時間  聯絡次數  消費價格指數  消費信心指數  訂購
0      31.0   服務業  單身  高中   手機   750.0     2  92.893   -46.2  一次
1      55.0    無業  已婚  高中   市話   154.0     8  94.465   -41.8  一次
2      27.0    主管  已婚  專科   手機   466.0     1  92.893   -46.2  頻繁
3      35.0    主管  已婚  大學   手機   222.0     1  93.075   -47.1  一次
4      29.0    藍領  單身  國中   手機    85.0     2  92.893   -46.2  頻繁
...     ...   ...  ..  ..  ...     ...   ...     ...     ...  ..
40995  47.0    主管  已婚  大學   市話    76.0     1  93.918   -42.7  偶爾
40996  30.0    主管  已婚  大學   手機   438.0     2  92.469   -33.6  從未
40997  48.0    藍領  已婚  小學   手機   151.0     1  93.918   -42.7  從未
40998  50.0    經理  已婚  大學   市話   242.0     2  94.465   -41.8  從未
40999  29.0  自僱人士  單身  大學   手機    88.0     1  93.200   -42.0  從未

[41000 rows x 10 columns]

In [4]:
df['學歷'].unique()

array(['高中', '專科', '大學', '國中', '小學', '未知', '文盲'], dtype=object)

In [5]:
dict3 = {'高中':1, '專科':2, '大學':3, '國中':4, '小學':5, '未知':6, '文盲':7}
df['學歷'] = df['學歷'].map(dict3)
df

         年齡    工作  婚姻  學歷 聯絡方式  最後聯絡時間  聯絡次數  消費價格指數  消費信心指數  訂購
0      31.0   服務業  單身   1   手機   750.0     2  92.893   -46.2  一次
1      55.0    無業  已婚   1   市話   154.0     8  94.465   -41.8  一次
2      27.0    主管  已婚   2   手機   466.0     1  92.893   -46.2  頻繁
3      35.0    主管  已婚   3   手機   222.0     1  93.075   -47.1  一次
4      29.0    藍領  單身   4   手機    85.0     2  92.893   -46.2  頻繁
...     ...   ...  ..  ..  ...     ...   ...     ...     ...  ..
40995  47.0    主管  已婚   3   市話    76.0     1  93.918   -42.7  偶爾
40996  30.0    主管  已婚   3   手機   438.0     2  92.469   -33.6  從未
40997  48.0    藍領  已婚   5   手機   151.0     1  93.918   -42.7  從未
40998  50.0    經理  已婚   3   市話   242.0     2  94.465   -41.8  從未
40999  29.0  自僱人士  單身   3   手機    88.0     1  93.200   -42.0  從未

[41000 rows x 10 columns]

# 使用Pandas 進行特徵選擇

## 皮爾森(Pearson) 相關係數

In [6]:
import pandas as pd
df = pd.read_csv('地區房價資料檔.csv')
featuresCorr = df.corr()
featuresCorr

,犯罪率,豪宅比,公設比,臨公園,NO濃度,房間數,屋齡,賣場距離,捷運距離,繳稅率,師生比,低收入比,房價
犯罪率,1.000000,-0.198184,0.403882,-0.056159,0.418423,-0.219135,0.350374,-0.378109,0.624691,0.581744,0.286694,0.453140,-0.386681
豪宅比,-0.198184,1.000000,-0.530497,-0.041534,-0.512648,0.315653,-0.567482,0.659829,-0.309246,-0.314601,-0.383729,-0.409970,0.363700
公設比,0.403882,-0.530497,1.000000,0.062161,0.760634,-0.391208,0.640189,-0.706669,0.592272,0.719742,0.373900,0.598912,-0.478614
臨公園,-0.056159,-0.041534,0.062161,1.000000,0.091162,0.094316,0.084713,-0.098918,-0.006554,-0.035305,-0.124759,-0.055581,0.179651
NO濃度,0.418423,-0.512648,0.760634,0.091162,1.000000,-0.302315,0.729869,-0.768413,0.607865,0.665860,0.176829,0.586526,-0.422592
房間數,-0.219135,0.315653,-0.391208,0.094316,-0.302315,1.000000,-0.232807,0.206958,-0.212325,-0.293659,-0.354519,-0.616665,0.696515
屋齡,0.350374,-0.567482,0.640189,0.084713,0.729869,-0.232807,1.000000,-0.748993,0.454357,0.505248,0.247797,0.596512,-0.364754
賣場距離,-0.378109,0.659829,-0.706669,-0.098918,-0.768413,0.206958,-0.748993,1.000000,-0.492819,-0.535611,-0.223204,-0.493881,0.247956
捷運距離,0.624691,-0.309246,0.592272,-0.006554,0.607865,-0.212325,0.454357,-0.492819,1.000000,0.909937,0.461487,0.484412,-0.377440
繳稅率,0.581744,-0.314601,0.719742,-0.035305,0.665860,-0.293659,0.505248,-0.535611,0.909937,1.000000,0.457685,0.540277,-0.464384
師生比,0.286694,-0.383729,0.373900,-0.124759,0.176829,-0.354519,0.247797,-0.223204,0.461487,0.457685,1.000000,0.365302,-0.504142
低收入比,0.453140,-0.409970,0.598912,-0.055581,0.586526,-0.616665,0.596512,-0.493881,0.484412,0.540277,0.365302,1.000000,-0.735179
房價,-0.386681,0.363700,-0.478614,0.179651,-0.422592,0.696515,-0.364754,0.247956,-0.377440,-0.464384,-0.504142,-0.735179,1.000000

In [7]:
targetCorr = featuresCorr['房價']
targetCorr = targetCorr.drop('房價')
selectedFeatures = targetCorr[abs(targetCorr) > 0.4]
print("選擇特徵數： {} \n選擇特徵:\n{}".
      format(len(selectedFeatures), selectedFeatures))

選擇特徵數： 6
選擇特徵:
公設比    -0.478614
NO濃度   -0.422592
房間數     0.696515
繳稅率    -0.464384
師生比    -0.504142
低收入比   -0.735179
Name: 房價, dtype: float64

## 肯德爾(Kendall) 相關係數

In [8]:
import pandas as pd
df = pd.read_csv('地區房價資料檔.csv')
featuresCorr = df.corr('kendall')
featuresCorr

,犯罪率,豪宅比,公設比,臨公園,NO濃度,房間數,屋齡,賣場距離,捷運距離,繳稅率,師生比,低收入比,房價
犯罪率,1.000000,-0.460379,0.520270,0.034488,0.603402,-0.215448,0.500570,-0.539368,0.563798,0.547322,0.312456,0.455192,-0.404431
豪宅比,-0.460379,1.000000,-0.531968,-0.038050,-0.506646,0.278587,-0.426987,0.474682,-0.233688,-0.291470,-0.356645,-0.383358,0.339110
公設比,0.520270,-0.531968,1.000000,0.075058,0.610078,-0.290649,0.486181,-0.563801,0.354393,0.484720,0.330475,0.462395,-0.415849
臨公園,0.034488,-0.038050,0.075058,1.000000,0.055708,0.050547,0.053710,-0.065191,0.023653,-0.037600,-0.117967,-0.042643,0.117118
NO濃度,0.603402,-0.506646,0.610078,0.055708,1.000000,-0.216459,0.589950,-0.683932,0.436235,0.454030,0.273242,0.449213,-0.393477
房間數,-0.215448,0.278587,-0.290649,0.050547,-0.216459,1.000000,-0.183353,0.180823,-0.081648,-0.192688,-0.220673,-0.469532,0.484126
屋齡,0.500570,-0.426987,0.486181,0.053710,0.589950,-0.183353,1.000000,-0.610570,0.310727,0.362669,0.245115,0.481129,-0.384108
賣場距離,-0.539368,0.474682,-0.563801,-0.065191,-0.683932,0.180823,-0.610570,1.000000,-0.362540,-0.384072,-0.218994,-0.407415,0.311898
捷運距離,0.563798,-0.233688,0.354393,0.023653,0.436235,-0.081648,0.310727,-0.362540,1.000000,0.558429,0.252236,0.290080,-0.248842
繳稅率,0.547322,-0.291470,0.484720,-0.037600,0.454030,-0.192688,0.362669,-0.384072,0.558429,1.000000,0.287771,0.384324,-0.413675
師生比,0.312456,-0.356645,0.330475,-0.117967,0.273242,-0.220673,0.245115,-0.218994,0.252236,0.287771,1.000000,0.324036,-0.394713
低收入比,0.455192,-0.383358,0.462395,-0.042643,0.449213,-0.469532,0.481129,-0.407415,0.290080,0.384324,0.324036,1.000000,-0.666242
房價,-0.404431,0.339110,-0.415849,0.117118,-0.393477,0.484126,-0.384108,0.311898,-0.248842,-0.413675,-0.394713,-0.666242,1.000000

In [9]:
targetCorr = featuresCorr['房價']
targetCorr = targetCorr.drop('房價')
selectedFeatures = targetCorr[abs(targetCorr) > 0.4]
print("選擇特徵數： {} \n選擇特徵:\n{}".
      format(len(selectedFeatures), selectedFeatures))

選擇特徵數： 5
選擇特徵:
犯罪率    -0.404431
公設比    -0.415849
房間數     0.484126
繳稅率    -0.413675
低收入比   -0.666242
Name: 房價, dtype: float64

## 斯皮爾曼(Spearman) 相關係數

In [10]:
import pandas as pd
df = pd.read_csv('地區房價資料檔.csv')
featuresCorr = df.corr('spearman')
featuresCorr

,犯罪率,豪宅比,公設比,臨公園,NO濃度,房間數,屋齡,賣場距離,捷運距離,繳稅率,師生比,低收入比,房價
犯罪率,1.000000,-0.569671,0.734762,0.042197,0.821355,-0.314092,0.706687,-0.744287,0.727641,0.731273,0.463736,0.634460,-0.558502
豪宅比,-0.569671,1.000000,-0.638285,-0.040454,-0.629175,0.361196,-0.541037,0.610052,-0.277894,-0.372251,-0.442181,-0.485576,0.436183
公設比,0.734762,-0.638285,1.000000,0.088866,0.788662,-0.413749,0.676212,-0.755432,0.456539,0.665352,0.427196,0.634162,-0.574273
臨公園,0.042197,-0.040454,0.088866,1.000000,0.067601,0.061829,0.065462,-0.079724,0.026749,-0.044428,-0.138738,-0.052163,0.142943
NO濃度,0.821355,-0.629175,0.788662,0.067601,1.000000,-0.310809,0.794984,-0.880266,0.587780,0.650474,0.384365,0.632562,-0.559078
房間數,-0.314092,0.361196,-0.413749,0.061829,-0.310809,1.000000,-0.272016,0.264631,-0.114412,-0.274610,-0.309278,-0.642547,0.635398
屋齡,0.706687,-0.541037,0.676212,0.065462,0.794984,-0.272016,1.000000,-0.802176,0.423539,0.528556,0.347743,0.652083,-0.542918
賣場距離,-0.744287,0.610052,-0.755432,-0.079724,-0.880266,0.264631,-0.802176,1.000000,-0.496508,-0.576185,-0.316907,-0.561163,0.443469
捷運距離,0.727641,-0.277894,0.456539,0.026749,0.587780,-0.114412,0.423539,-0.496508,1.000000,0.705047,0.318965,0.396541,-0.347042
繳稅率,0.731273,-0.372251,0.665352,-0.044428,0.650474,-0.274610,0.528556,-0.576185,0.705047,1.000000,0.453059,0.533801,-0.560836
師生比,0.463736,-0.442181,0.427196,-0.138738,0.384365,-0.309278,0.347743,-0.316907,0.318965,0.453059,1.000000,0.459183,-0.550923
低收入比,0.634460,-0.485576,0.634162,-0.052163,0.632562,-0.642547,0.652083,-0.561163,0.396541,0.533801,0.459183,1.000000,-0.850714
房價,-0.558502,0.436183,-0.574273,0.142943,-0.559078,0.635398,-0.542918,0.443469,-0.347042,-0.560836,-0.550923,-0.850714,1.000000

In [11]:
targetCorr = featuresCorr['房價']
targetCorr = targetCorr.drop('房價')
selectedFeatures = targetCorr[abs(targetCorr) > 0.4]
print("選擇特徵數： {} \n選擇特徵:\n{}".
      format(len(selectedFeatures), selectedFeatures))

選擇特徵數： 10
選擇特徵:
犯罪率    -0.558502
豪宅比     0.436183
公設比    -0.574273
NO濃度   -0.559078
房間數     0.635398
屋齡     -0.542918
賣場距離    0.443469
繳稅率    -0.560836
師生比    -0.550923
低收入比   -0.850714
Name: 房價, dtype: float64